### ISSUE TITLE
Possibility to use to avoid idle state

### ISSUE THREAD

**Issue by giokara** [PanayotCankov/nativescript-idle#1]
Hi @PanayotCankov, this package seems to be one of the limited options to work long-term in NativeScript apps without user interaction.
Can this also be used to avoid going into idle state to e.g. keep a socket connection alive? If yes, how could this be achieved?
Thanks in advance!

**Comment by PanayotCankov** [comment]
Hi,
No, it won't keep your app awake. You may be looking for something like "background mode" for iOS or something?

**Comment by giokara** [comment]
Too bad, my fault. Thanks for the fast response!
